/**
 * @generated
 */
module.exports = {
  "argo-commands": {
    "id": "argo-commands",
    "title": "Argo commands",
    "source": "argo-commands.md",
    "permalink": "docs/argo-commands.html",
    "localized_id": "argo-commands",
    "language": "en",
    "sidebar": "docs",
    "category": "Kubernetes workflows",
    "subcategory": null,
    "order": 31,
    "next_id": "argo-debug",
    "next": "argo-debug",
    "previous_id": "argo-run",
    "previous": "argo-run",
    "previous_title": "Run Argo workflows",
    "next_title": "Debug Argo workflow"
  },
  "argo-debug": {
    "id": "argo-debug",
    "title": "Debug Argo workflow",
    "source": "argo-debug.md",
    "permalink": "docs/argo-debug.html",
    "localized_id": "argo-debug",
    "language": "en",
    "sidebar": "docs",
    "category": "Kubernetes workflows",
    "subcategory": null,
    "order": 32,
    "next_id": "argo-secret",
    "next": "argo-secret",
    "previous_id": "argo-commands",
    "previous": "argo-commands",
    "previous_title": "Argo commands",
    "next_title": "Use OpenShift secrets"
  },
  "argo-install": {
    "id": "argo-install",
    "title": "Argo installation",
    "sidebar_label": "Argo installation",
    "source": "argo-install.md",
    "permalink": "docs/argo-install.html",
    "localized_id": "argo-install",
    "language": "en",
    "sidebar": "docs",
    "category": "Kubernetes workflows",
    "subcategory": null,
    "order": 27,
    "next_id": "argo-login",
    "next": "argo-login",
    "previous_id": "guide-mysql",
    "previous": "guide-mysql",
    "previous_title": "Setting up MySQL",
    "next_title": "Login to OpenShift"
  },
  "argo-login": {
    "id": "argo-login",
    "title": "Login to OpenShift",
    "source": "argo-login.md",
    "permalink": "docs/argo-login.html",
    "localized_id": "argo-login",
    "language": "en",
    "sidebar": "docs",
    "category": "Kubernetes workflows",
    "subcategory": null,
    "order": 28,
    "next_id": "argo-volume",
    "next": "argo-volume",
    "previous_id": "argo-install",
    "previous": "argo-install",
    "previous_title": "Argo installation",
    "next_title": "Define volumes"
  },
  "argo-run": {
    "id": "argo-run",
    "title": "Run Argo workflows",
    "source": "argo-run.md",
    "permalink": "docs/argo-run.html",
    "localized_id": "argo-run",
    "language": "en",
    "sidebar": "docs",
    "category": "Kubernetes workflows",
    "subcategory": null,
    "order": 30,
    "next_id": "argo-commands",
    "next": "argo-commands",
    "previous_id": "argo-volume",
    "previous": "argo-volume",
    "previous_title": "Define volumes",
    "next_title": "Argo commands"
  },
  "argo-secret": {
    "id": "argo-secret",
    "title": "Use OpenShift secrets",
    "source": "argo-secret.md",
    "permalink": "docs/argo-secret.html",
    "localized_id": "argo-secret",
    "language": "en",
    "sidebar": "docs",
    "category": "Kubernetes workflows",
    "subcategory": null,
    "order": 33,
    "previous_id": "argo-debug",
    "previous": "argo-debug",
    "previous_title": "Debug Argo workflow"
  },
  "argo-volume": {
    "id": "argo-volume",
    "title": "Define volumes",
    "source": "argo-volume.md",
    "permalink": "docs/argo-volume.html",
    "localized_id": "argo-volume",
    "language": "en",
    "sidebar": "docs",
    "category": "Kubernetes workflows",
    "subcategory": null,
    "order": 29,
    "next_id": "argo-run",
    "next": "argo-run",
    "previous_id": "argo-login",
    "previous": "argo-login",
    "previous_title": "Login to OpenShift",
    "next_title": "Run Argo workflows"
  },
  "cwl-create": {
    "id": "cwl-create",
    "title": "Create a CWL tool",
    "source": "cwl-create.md",
    "permalink": "docs/cwl-create.html",
    "localized_id": "cwl-create",
    "language": "en",
    "sidebar": "docs",
    "category": "Guides",
    "subcategory": null,
    "order": 19,
    "next_id": "guide-docker",
    "next": "guide-docker",
    "previous_id": "guide-filebrowser",
    "previous": "guide-filebrowser",
    "previous_title": "Filebrowser utilities",
    "next_title": "Docker guide"
  },
  "d2s-biothings": {
    "id": "d2s-biothings",
    "title": "Use BioThings Studio",
    "source": "d2s-biothings.md",
    "permalink": "docs/d2s-biothings.html",
    "localized_id": "d2s-biothings",
    "language": "en",
    "sidebar": "docs",
    "category": "Integrate data",
    "subcategory": null,
    "order": 14,
    "next_id": "guide-ontology",
    "next": "guide-ontology",
    "previous_id": "d2s-dipper",
    "previous": "d2s-dipper",
    "previous_title": "Use Monarch Dipper",
    "next_title": "Choose an ontology"
  },
  "d2s-dipper": {
    "id": "d2s-dipper",
    "title": "Use Monarch Dipper",
    "source": "d2s-dipper.md",
    "permalink": "docs/d2s-dipper.html",
    "localized_id": "d2s-dipper",
    "language": "en",
    "sidebar": "docs",
    "category": "Integrate data",
    "subcategory": null,
    "order": 13,
    "next_id": "d2s-biothings",
    "next": "d2s-biothings",
    "previous_id": "d2s-run",
    "previous": "d2s-run",
    "previous_title": "Run CWL workflows",
    "next_title": "Use BioThings Studio"
  },
  "d2s-installation": {
    "id": "d2s-installation",
    "title": "Installation",
    "source": "d2s-installation.md",
    "permalink": "docs/d2s-installation.html",
    "localized_id": "d2s-installation",
    "language": "en",
    "sidebar": "docs",
    "category": "Get started",
    "subcategory": null,
    "order": 2,
    "next_id": "d2s-workspace",
    "next": "d2s-workspace",
    "previous_id": "d2s-introduction",
    "previous": "d2s-introduction",
    "previous_title": "Introduction",
    "next_title": "Initialize and update"
  },
  "d2s-interfaces": {
    "id": "d2s-interfaces",
    "title": "Deploy interfaces",
    "source": "d2s-interfaces.md",
    "permalink": "docs/d2s-interfaces.html",
    "localized_id": "d2s-interfaces",
    "language": "en"
  },
  "d2s-introduction": {
    "id": "d2s-introduction",
    "title": "Introduction",
    "sidebar_label": "Introduction",
    "source": "d2s-introduction.md",
    "permalink": "docs/d2s-introduction.html",
    "localized_id": "d2s-introduction",
    "language": "en",
    "sidebar": "docs",
    "category": "Get started",
    "subcategory": null,
    "order": 1,
    "next_id": "d2s-installation",
    "next": "d2s-installation",
    "next_title": "Installation"
  },
  "d2s-new-dataset": {
    "id": "d2s-new-dataset",
    "title": "Add a new dataset",
    "source": "d2s-new-dataset.md",
    "permalink": "docs/d2s-new-dataset.html",
    "localized_id": "d2s-new-dataset",
    "language": "en",
    "sidebar": "docs",
    "category": "Integrate data",
    "subcategory": null,
    "order": 10,
    "next_id": "d2s-rml",
    "next": "d2s-rml",
    "previous_id": "translator-prototypes-registry",
    "previous": "translator-prototypes-registry",
    "previous_title": "Translator Prototypes",
    "next_title": "Run RML transformations"
  },
  "d2s-rml": {
    "id": "d2s-rml",
    "title": "Run RML transformations",
    "source": "d2s-rml.md",
    "permalink": "docs/d2s-rml.html",
    "localized_id": "d2s-rml",
    "language": "en",
    "sidebar": "docs",
    "category": "Integrate data",
    "subcategory": null,
    "order": 11,
    "next_id": "d2s-run",
    "next": "d2s-run",
    "previous_id": "d2s-new-dataset",
    "previous": "d2s-new-dataset",
    "previous_title": "Add a new dataset",
    "next_title": "Run CWL workflows"
  },
  "d2s-run": {
    "id": "d2s-run",
    "title": "Run CWL workflows",
    "source": "d2s-run.md",
    "permalink": "docs/d2s-run.html",
    "localized_id": "d2s-run",
    "language": "en",
    "sidebar": "docs",
    "category": "Integrate data",
    "subcategory": null,
    "order": 12,
    "next_id": "d2s-dipper",
    "next": "d2s-dipper",
    "previous_id": "d2s-rml",
    "previous": "d2s-rml",
    "previous_title": "Run RML transformations",
    "next_title": "Use Monarch Dipper"
  },
  "d2s-services": {
    "id": "d2s-services",
    "title": "Start services",
    "source": "d2s-services.md",
    "permalink": "docs/d2s-services.html",
    "localized_id": "d2s-services",
    "language": "en",
    "sidebar": "docs",
    "category": "Get started",
    "subcategory": null,
    "order": 5,
    "next_id": "services-graph-databases",
    "next": "services-graph-databases",
    "previous_id": "d2s-services",
    "previous": "d2s-services",
    "previous_title": "Start services",
    "next_title": "Graph databases"
  },
  "d2s-workspace": {
    "id": "d2s-workspace",
    "title": "Initialize and update",
    "source": "d2s-workspace.md",
    "permalink": "docs/d2s-workspace.html",
    "localized_id": "d2s-workspace",
    "language": "en",
    "sidebar": "docs",
    "category": "Get started",
    "subcategory": null,
    "order": 3,
    "next_id": "d2s-services",
    "next": "d2s-services",
    "previous_id": "d2s-installation",
    "previous": "d2s-installation",
    "previous_title": "Installation",
    "next_title": "Start services"
  },
  "guide-deploy-app": {
    "id": "guide-deploy-app",
    "title": "Deploy services publicly",
    "source": "guide-deploy-app.md",
    "permalink": "docs/guide-deploy-app.html",
    "localized_id": "guide-deploy-app",
    "language": "en",
    "sidebar": "docs",
    "category": "Guides",
    "subcategory": null,
    "order": 17,
    "next_id": "guide-filebrowser",
    "next": "guide-filebrowser",
    "previous_id": "guide-preprocessing",
    "previous": "guide-preprocessing",
    "previous_title": "Preprocess input files",
    "next_title": "Filebrowser utilities"
  },
  "guide-docker": {
    "id": "guide-docker",
    "title": "Docker guide",
    "source": "guide-docker.md",
    "permalink": "docs/guide-docker.html",
    "localized_id": "guide-docker",
    "language": "en",
    "sidebar": "docs",
    "category": "Guides",
    "subcategory": null,
    "order": 20,
    "next_id": "guide-jenkins",
    "next": "guide-jenkins",
    "previous_id": "cwl-create",
    "previous": "cwl-create",
    "previous_title": "Create a CWL tool",
    "next_title": "Experimental Jenkins workflows"
  },
  "guide-filebrowser": {
    "id": "guide-filebrowser",
    "title": "Filebrowser utilities",
    "source": "guide-filebrowser.md",
    "permalink": "docs/guide-filebrowser.html",
    "localized_id": "guide-filebrowser",
    "language": "en",
    "sidebar": "docs",
    "category": "Guides",
    "subcategory": null,
    "order": 18,
    "next_id": "cwl-create",
    "next": "cwl-create",
    "previous_id": "guide-deploy-app",
    "previous": "guide-deploy-app",
    "previous_title": "Deploy services publicly",
    "next_title": "Create a CWL tool"
  },
  "guide-github-actions": {
    "id": "guide-github-actions",
    "title": "GitHub Actions workflows",
    "source": "guide-github-actions.md",
    "permalink": "docs/guide-github-actions.html",
    "localized_id": "guide-github-actions",
    "language": "en"
  },
  "guide-graphdb": {
    "id": "guide-graphdb",
    "title": "Setting up GraphDB",
    "source": "guide-graphdb.md",
    "permalink": "docs/guide-graphdb.html",
    "localized_id": "guide-graphdb",
    "language": "en",
    "sidebar": "docs",
    "category": "Guides",
    "subcategory": "Setup databases",
    "order": 22,
    "next_id": "guide-virtuoso",
    "next": "guide-virtuoso",
    "previous_id": "guide-jenkins",
    "previous": "guide-jenkins",
    "previous_title": "Experimental Jenkins workflows",
    "next_title": "Setting up Virtuoso"
  },
  "guide-jenkins": {
    "id": "guide-jenkins",
    "title": "Experimental Jenkins workflows",
    "source": "guide-jenkins.md",
    "permalink": "docs/guide-jenkins.html",
    "localized_id": "guide-jenkins",
    "language": "en",
    "sidebar": "docs",
    "category": "Guides",
    "subcategory": null,
    "order": 21,
    "next_id": "guide-graphdb",
    "next": "guide-graphdb",
    "previous_id": "guide-docker",
    "previous": "guide-docker",
    "previous_title": "Docker guide",
    "next_title": "Setting up GraphDB"
  },
  "guide-mariadb": {
    "id": "guide-mariadb",
    "title": "Setting up MariaDB",
    "source": "guide-mariadb.md",
    "permalink": "docs/guide-mariadb.html",
    "localized_id": "guide-mariadb",
    "language": "en",
    "sidebar": "docs",
    "category": "Guides",
    "subcategory": "Setup databases",
    "order": 25,
    "next_id": "guide-mysql",
    "next": "guide-mysql",
    "previous_id": "guide-postgres",
    "previous": "guide-postgres",
    "previous_title": "Setting up PostgreSQL",
    "next_title": "Setting up MySQL"
  },
  "guide-mysql": {
    "id": "guide-mysql",
    "title": "Setting up MySQL",
    "source": "guide-mysql.md",
    "permalink": "docs/guide-mysql.html",
    "localized_id": "guide-mysql",
    "language": "en",
    "sidebar": "docs",
    "category": "Guides",
    "subcategory": "Setup databases",
    "order": 26,
    "next_id": "argo-install",
    "next": "argo-install",
    "previous_id": "guide-mariadb",
    "previous": "guide-mariadb",
    "previous_title": "Setting up MariaDB",
    "next_title": "Argo installation"
  },
  "guide-ontology": {
    "id": "guide-ontology",
    "title": "Choose an ontology",
    "source": "guide-ontology.md",
    "permalink": "docs/guide-ontology.html",
    "localized_id": "guide-ontology",
    "language": "en",
    "sidebar": "docs",
    "category": "Guides",
    "subcategory": null,
    "order": 15,
    "next_id": "guide-preprocessing",
    "next": "guide-preprocessing",
    "previous_id": "d2s-biothings",
    "previous": "d2s-biothings",
    "previous_title": "Use BioThings Studio",
    "next_title": "Preprocess input files"
  },
  "guide-postgres": {
    "id": "guide-postgres",
    "title": "Setting up PostgreSQL",
    "source": "guide-postgres.md",
    "permalink": "docs/guide-postgres.html",
    "localized_id": "guide-postgres",
    "language": "en",
    "sidebar": "docs",
    "category": "Guides",
    "subcategory": "Setup databases",
    "order": 24,
    "next_id": "guide-mariadb",
    "next": "guide-mariadb",
    "previous_id": "guide-virtuoso",
    "previous": "guide-virtuoso",
    "previous_title": "Setting up Virtuoso",
    "next_title": "Setting up MariaDB"
  },
  "guide-preprocessing": {
    "id": "guide-preprocessing",
    "title": "Preprocess input files",
    "source": "guide-preprocessing.md",
    "permalink": "docs/guide-preprocessing.html",
    "localized_id": "guide-preprocessing",
    "language": "en",
    "sidebar": "docs",
    "category": "Guides",
    "subcategory": null,
    "order": 16,
    "next_id": "guide-deploy-app",
    "next": "guide-deploy-app",
    "previous_id": "guide-ontology",
    "previous": "guide-ontology",
    "previous_title": "Choose an ontology",
    "next_title": "Deploy services publicly"
  },
  "guide-virtuoso": {
    "id": "guide-virtuoso",
    "title": "Setting up Virtuoso",
    "source": "guide-virtuoso.md",
    "permalink": "docs/guide-virtuoso.html",
    "localized_id": "guide-virtuoso",
    "language": "en",
    "sidebar": "docs",
    "category": "Guides",
    "subcategory": "Setup databases",
    "order": 23,
    "next_id": "guide-postgres",
    "next": "guide-postgres",
    "previous_id": "guide-graphdb",
    "previous": "guide-graphdb",
    "previous_title": "Setting up GraphDB",
    "next_title": "Setting up PostgreSQL"
  },
  "services-graph-databases": {
    "id": "services-graph-databases",
    "title": "Graph databases",
    "source": "services-graph-databases.md",
    "permalink": "docs/services-graph-databases.html",
    "localized_id": "services-graph-databases",
    "language": "en",
    "sidebar": "docs",
    "category": "Get started",
    "subcategory": null,
    "order": 6,
    "next_id": "services-interfaces",
    "next": "services-interfaces",
    "previous_id": "d2s-services",
    "previous": "d2s-services",
    "previous_title": "Start services",
    "next_title": "Interfaces"
  },
  "services-interfaces": {
    "id": "services-interfaces",
    "title": "Interfaces",
    "source": "services-interfaces.md",
    "permalink": "docs/services-interfaces.html",
    "localized_id": "services-interfaces",
    "language": "en",
    "sidebar": "docs",
    "category": "Get started",
    "subcategory": null,
    "order": 7,
    "next_id": "services-utilities",
    "next": "services-utilities",
    "previous_id": "services-graph-databases",
    "previous": "services-graph-databases",
    "previous_title": "Graph databases",
    "next_title": "Utilities"
  },
  "services-utilities": {
    "id": "services-utilities",
    "title": "Utilities",
    "source": "services-utilities.md",
    "permalink": "docs/services-utilities.html",
    "localized_id": "services-utilities",
    "language": "en",
    "sidebar": "docs",
    "category": "Get started",
    "subcategory": null,
    "order": 8,
    "next_id": "translator-prototypes-registry",
    "next": "translator-prototypes-registry",
    "previous_id": "services-interfaces",
    "previous": "services-interfaces",
    "previous_title": "Interfaces",
    "next_title": "Translator Prototypes"
  },
  "translator-prototypes-registry": {
    "id": "translator-prototypes-registry",
    "title": "Translator Prototypes",
    "source": "translator-prototypes-registry.md",
    "permalink": "docs/translator-prototypes-registry.html",
    "localized_id": "translator-prototypes-registry",
    "language": "en",
    "sidebar": "docs",
    "category": "Get started",
    "subcategory": null,
    "order": 9,
    "next_id": "d2s-new-dataset",
    "next": "d2s-new-dataset",
    "previous_id": "services-utilities",
    "previous": "services-utilities",
    "previous_title": "Utilities",
    "next_title": "Add a new dataset"
  }
};
