name: Publish to GitHub Pages

on:
  # release:
  #   types:
  #     - created
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
        host: github.com
        private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}

    - name: Build and publish
      run: |
        git config --global user.email "vincent.emonet@maastrichtuniversity.nl"
        git config --global user.name "Vincent Emonet"
        cd website
        yarn install
        yarn build
        GIT_USER=MaastrichtU-IDS CURRENT_BRANCH=master USE_SSH=true yarn run publish-gh-pages

    - id: fix_custom_url
      uses: octokit/request-action@v2.x
      with:
        route: PUT /repos/:owner/:repo/pages
        mediaType: | # The | is significant!
          previews: 
            - switcheroo
        cname: "d2s.semanticscience.org"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}